name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
        
    - name: Install deps
      run: go get -u github.com/aws/aws-sdk-go && go get -u github.com/docker/engine && go get -u github.com/docker/docker/client && go get -u github.com/docker/engine-api && go get -u github.com/docker/distribution/ && go get -u github.com/docker/go-connections && go get -u github.com/docker/go-units

    - name: Build
      run: CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o ecs-status-manager -ldflags '-w -s' ./main/ecs-status-manager.go 
